name: Deploy and Notify

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for manual deployment'
        required: true
        type: string

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get release information
        id: release_info
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            
            # Handle multi-line body properly
            BODY=$(echo "${{ github.event.release.body }}" | head -c 500 | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
            echo "body=$BODY" >> $GITHUB_OUTPUT
            
            echo "url=${{ github.event.release.html_url }}" >> $GITHUB_OUTPUT
            echo "name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "body=Manual deployment triggered" >> $GITHUB_OUTPUT
            echo "url=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "name=SRLU ${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Create RGX Mods standard Discord message
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"@everyone\",
                 \"username\": \"SRLU Update\",
                 \"avatar_url\": \"https://raw.githubusercontent.com/donniedice/SRLU/main/images/SRLU_logo_400x400.png\",
                 \"embeds\": [{
                   \"title\": \"🗡️ SRLU | Skyrim Level-Up! - ${{ steps.release_info.outputs.version }}\",
                   \"description\": \"**Fus Ro DAH!** - A new version of SRLU has been released!\\n\\n🎵 **What's New:**\\n• Documentation overhaul with RGX Mods Brand Standards\\n• Discord webhook notifications\\n• Complete CurseForge description\\n• Updated README with proper formatting\\n\\n**Transform your WoW leveling experience with the iconic Skyrim level-up sound!**\",
                   \"url\": \"${{ steps.release_info.outputs.url }}\",
                   \"color\": 9132843,
                   \"thumbnail\": {
                     \"url\": \"https://raw.githubusercontent.com/donniedice/SRLU/main/images/SRLU_logo_400x400.png\"
                   },
                   \"fields\": [
                     {
                       \"name\": \"📥 Downloads\",
                       \"value\": \"[CurseForge](https://www.curseforge.com/wow/addons/srlu)\\n[Wago.io](https://addons.wago.io/addons/srlu)\\n[GitHub](https://github.com/donniedice/SRLU)\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"🎮 Compatibility\",
                       \"value\": \"✅ The War Within\\n✅ Classic Era\\n✅ Cataclysm\\n✅ MoP\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"💬 Support\",
                       \"value\": \"[Join Discord](https://discord.gg/N7kdKAHVVF)\\n[Report Issues](https://github.com/donniedice/SRLU/issues)\",
                       \"inline\": true
                     }
                   ],
                   \"footer\": {
                     \"text\": \"RGX Mods - RealmGX Community\",
                     \"icon_url\": \"https://raw.githubusercontent.com/donniedice/SimpleQuestPlates/main/images/kiwi.gif\"
                   },
                   \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
                 }]
               }" \
               "$DISCORD_WEBHOOK"
      
      - name: Deploy to CurseForge
        if: github.event_name == 'release'
        env:
          CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
        run: |
          echo "CurseForge deployment would happen here"
          echo "This step requires the CurseForge API token to be configured"
          # Add actual CurseForge deployment logic here when API token is available
      
      - name: Deploy to Wago
        if: github.event_name == 'release'
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        run: |
          echo "Wago deployment would happen here"
          echo "This step requires the Wago API token to be configured"
          # Add actual Wago deployment logic here when API token is available